name: "main.stop"
description: "Stop the main AI loop so the user can answer you or ask you something."
developer: "standart libary"
project: "stop"
parameters:
  - name: "reason"
    type: "string"
    required: false
    description: ""
usage_examples:
  - '{tool main.stop}'
