name: "main.speak"
description: "returns a message to the user"
developer: "main"
project: "speak"
parameters:
  - name: "text"
    type: "string"
    required: true
    description: "The text to return to the user"
usage_examples:
  - '{tool main.speak text="Hello World"}'
  - '{tool main.speak text="Task completed successfully"}'
